export const apiRoutes = {
  publicConfig: '/api/v1/public/config',
  services: '/api/v1/services',
  service: (slug: string) => `/api/v1/services/${encodeURIComponent(slug)}`,
  courses: '/api/v1/courses',
  course: (slug: string) => `/api/v1/courses/${encodeURIComponent(slug)}`,
  courseSessions: (id: string) => `/api/v1/courses/${encodeURIComponent(id)}/sessions`,
  spaces: '/api/v1/spaces',
  space: (slug: string) => `/api/v1/spaces/${encodeURIComponent(slug)}`,
  availability: '/api/v1/availability',
  bookings: '/api/v1/bookings',
  booking: (reference: string) => `/api/v1/bookings/${encodeURIComponent(reference)}`,
  requests: '/api/v1/requests',
  login: '/api/v1/auth/login', logout: '/api/v1/auth/logout', me: '/api/v1/auth/me', csrf: '/api/v1/auth/csrf',
  operationsSummary: '/api/v1/operations/summary',
  operationsRequests: '/api/v1/operations/requests',
  operationsRequest: (id: string) => `/api/v1/operations/requests/${encodeURIComponent(id)}`,
  operationsRequestStatus: (id: string) => `/api/v1/operations/requests/${encodeURIComponent(id)}/status`,
  operationsBookings: '/api/v1/operations/bookings',
  operationsBooking: (id: string) => `/api/v1/operations/bookings/${encodeURIComponent(id)}`,
  operationsBookingStatus: (id: string) => `/api/v1/operations/bookings/${encodeURIComponent(id)}/status`,
  operationsCustomers: '/api/v1/operations/customers',
  operationsCustomer: (id: string) => `/api/v1/operations/customers/${encodeURIComponent(id)}`,
  operationsTasks: '/api/v1/operations/tasks',
  operationsTask: (id: string) => `/api/v1/operations/tasks/${encodeURIComponent(id)}`,
  operationsTaskStatus: (id: string) => `/api/v1/operations/tasks/${encodeURIComponent(id)}/status`,
  operationsAvailabilityRules: '/api/v1/operations/availability/rules',
  operationsAvailabilityRule: (id: string) => `/api/v1/operations/availability/rules/${encodeURIComponent(id)}`,
  operationsAvailabilityExceptions: '/api/v1/operations/availability/exceptions',
  operationsAvailabilityException: (id: string) => `/api/v1/operations/availability/exceptions/${encodeURIComponent(id)}`,
  operationsBlockedPeriods: '/api/v1/operations/availability/blocked-periods',
  operationsBlockedPeriod: (id: string) => `/api/v1/operations/availability/blocked-periods/${encodeURIComponent(id)}`,
  operationsAdminServices: '/api/v1/operations/catalog/services',
  operationsAdminService: (id: string) => `/api/v1/operations/catalog/services/${encodeURIComponent(id)}`,
  operationsAdminCourses: '/api/v1/operations/catalog/courses',
  operationsAdminCourse: (id: string) => `/api/v1/operations/catalog/courses/${encodeURIComponent(id)}`,
  operationsAdminCourseSessions: (courseId: string) => `/api/v1/operations/catalog/courses/${encodeURIComponent(courseId)}/sessions`,
  operationsAdminCourseSession: (courseId: string, id: string) => `/api/v1/operations/catalog/courses/${encodeURIComponent(courseId)}/sessions/${encodeURIComponent(id)}`,
  operationsAdminSpaces: '/api/v1/operations/catalog/spaces',
  operationsAdminSpace: (id: string) => `/api/v1/operations/catalog/spaces/${encodeURIComponent(id)}`,
  operationsAdminUsers: '/api/v1/operations/access/users',
  operationsAdminUser: (id: string) => `/api/v1/operations/access/users/${encodeURIComponent(id)}`,
  operationsAdminRoles: '/api/v1/operations/access/roles',
  operationsAdminRole: (id: string) => `/api/v1/operations/access/roles/${encodeURIComponent(id)}`,
  operationsAdminPermissions: '/api/v1/operations/access/permissions',
  operationsGeneralSettings: '/api/v1/operations/settings/general',
} as const
