export const apiRoutes = {
  publicConfig: '/api/v1/public/config',
  services: '/api/v1/services',
  service: (slug: string) => `/api/v1/services/${encodeURIComponent(slug)}`,
  courses: '/api/v1/courses',
  course: (slug: string) => `/api/v1/courses/${encodeURIComponent(slug)}`,
  courseSessions: (id: string) => `/api/v1/courses/${encodeURIComponent(id)}/sessions`,
  spaces: '/api/v1/spaces',
  space: (slug: string) => `/api/v1/spaces/${encodeURIComponent(slug)}`,
  availability: '/api/v1/availability',
  bookings: '/api/v1/bookings',
  booking: (reference: string) => `/api/v1/bookings/${encodeURIComponent(reference)}`,
  requests: '/api/v1/requests',
  login: '/api/v1/auth/login',
  logout: '/api/v1/auth/logout',
  me: '/api/v1/auth/me',
  csrf: '/api/v1/auth/csrf',
  operationsSummary: '/api/v1/operations/summary',
  operationsRequests: '/api/v1/operations/requests',
  operationsRequest: (id: string) => `/api/v1/operations/requests/${encodeURIComponent(id)}`,
  operationsRequestStatus: (id: string) => `/api/v1/operations/requests/${encodeURIComponent(id)}/status`,
  operationsBookings: '/api/v1/operations/bookings',
  operationsBooking: (id: string) => `/api/v1/operations/bookings/${encodeURIComponent(id)}`,
  operationsBookingStatus: (id: string) => `/api/v1/operations/bookings/${encodeURIComponent(id)}/status`,
  operationsCustomers: '/api/v1/operations/customers',
  operationsCustomer: (id: string) => `/api/v1/operations/customers/${encodeURIComponent(id)}`,
  operationsAvailabilityRules: '/api/v1/operations/availability/rules',
  operationsAvailabilityRule: (id: string) => `/api/v1/operations/availability/rules/${encodeURIComponent(id)}`,
  operationsAvailabilityExceptions: '/api/v1/operations/availability/exceptions',
  operationsAvailabilityException: (id: string) => `/api/v1/operations/availability/exceptions/${encodeURIComponent(id)}`,
  operationsBlockedPeriods: '/api/v1/operations/availability/blocked-periods',
  operationsBlockedPeriod: (id: string) => `/api/v1/operations/availability/blocked-periods/${encodeURIComponent(id)}`,
} as const
