import { createRoot } from 'react-dom/client'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { PublicLayout } from './app/layouts/Layouts'
import { HomeEntry } from './features/home/components/HomeEntry'
import './styles/global.css'
import './design-system/tokens/public-contract.css'
import './styles/public-v2.css'
import './styles/public-pages-v2.css'
import './styles/course-system.css'
import './styles/spaces-v2.css'
import './styles/booking-v2.css'
import './styles/operations-v2.css'
import './styles/operations-data.css'
import './styles/availability-admin.css'
import './styles/catalog-admin.css'
import './styles/access-admin.css'
import './styles/secretary-dashboard.css'
import './styles/owner-executive.css'
import './styles/platform-admin.css'
import './styles/motion-foundation.css'
import './styles/accessibility-foundation.css'
import './styles/public-visual-foundations.css'
import './styles/public-navigation-hero.css'
import './styles/public-services-experience.css'
import './styles/public-training-experience.css'
import './features/courses/training-active-knowledge.css'
import './styles/founder-launch.css'
import './styles/home-founder.css'
import './styles/public-design-lock.css'
import './features/home/home-spatial-stage-v3.css'
import './styles/public-visual-system-v3.css'
import './features/courses/training-spatial-stage-v3.css'
import './features/spaces/spaces-spatial-stage-v3.css'
import './features/services/services-spatial-stage-v3.css'
import './features/home/about-spatial-stage-v3.css'
import './features/contact/contact-spatial-stage-v3.css'
import './features/booking/booking-spatial-stage-v3.css'
import './styles/public-foundations.css'

// Standalone development entry; not imported by the application or production build.
const requested = Number(new URLSearchParams(window.location.search).get('phase'))
const phase: 0 | 1 | 2 | 3 = requested === 1 || requested === 2 || requested === 3 ? requested : 0
if (import.meta.env.DEV) {
  createRoot(document.getElementById('root')!).render(<MemoryRouter><Routes><Route element={<PublicLayout />}><Route index element={<div className="home-v2"><HomeEntry reviewPhase={phase} /></div>} /></Route></Routes></MemoryRouter>)
}