import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './app/App'
import { AppProviders } from './app/providers/AppProviders'
import './styles/global.css'
import './styles/public-v2.css'
import './styles/public-pages-v2.css'
import './styles/course-system.css'
import './styles/spaces-v2.css'
import './styles/booking-v2.css'
import './styles/operations-v2.css'
import './styles/operations-data.css'
import './styles/availability-admin.css'
import './styles/catalog-admin.css'
import './styles/access-admin.css'
import './styles/secretary-dashboard.css'
import './styles/owner-executive.css'
import './styles/platform-admin.css'
import './styles/motion-foundation.css'
import './styles/accessibility-foundation.css'
import './styles/public-visual-foundations.css'
import './styles/public-navigation-hero.css'
import './styles/public-services-experience.css'
import './styles/public-training-experience.css'
import './features/courses/training-active-knowledge.css'
import './styles/founder-launch.css'
import './styles/home-founder.css'
import './styles/public-design-lock.css'
import './styles/public-visual-system-v3.css'
import './features/spaces/spaces-spatial-stage-v3.css'
import './features/home/about-spatial-stage-v3.css'
import './features/contact/contact-spatial-stage-v3.css'
import './features/booking/booking-spatial-stage-v3.css'
import './styles/public-v3-critical-refinement.css'
import './styles/public-v3-product-finish.css'
import './styles/public-v3-testimonial-proof.css'
import './features/services/services-spatial-stage-v3.css'
import './features/courses/training-spatial-stage-v3.css'
import './features/home/home-spatial-stage-v3.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <AppProviders>
      <App />
    </AppProviders>
  </StrictMode>,
)
