import { useState } from 'react'
import { Info, MoreHorizontal, Plus, Trash2 } from 'lucide-react'
import { Alert, BottomSheet, ConfirmDialog, Dialog, Drawer, DropdownMenu, EmptyState, ErrorState, LoadingState, Popover, Tooltip } from '../../design-system/patterns/feedback-overlays'
import { ActiveFilterChips, FilterButton, FilterGroup, SearchToolbar } from '../../design-system/patterns/filters'
import { BookingStepper, CalendarFoundation, DatePicker, TimeSlotGroup } from '../../design-system/patterns/booking'
import { ActivityList, DefinitionList, EntityCard, ResponsiveEntityList } from '../../design-system/patterns/data'
import { Breadcrumbs, Pagination, Tabs } from '../../design-system/patterns/navigation'
import { FormActions, FormSection, FormSummary } from '../../design-system/patterns/forms'
import { Avatar, Badge, Button, Checkbox, Divider, IconButton, Radio, SearchInput, Select, Skeleton, Spinner, Switch, Textarea, TextField } from '../../design-system/primitives'

const rows = [{ id: '1', name: '[CONTENT TBD]', status: 'A confirmar' }, { id: '2', name: '[CONTENT TBD]', status: 'A confirmar' }]

export function ComponentLab() {
  const [dialog, setDialog] = useState(false)
  const [drawer, setDrawer] = useState(false)
  const [sheet, setSheet] = useState(false)
  const [chips, setChips] = useState([{ id: 'pending', label: 'A confirmar' }])
  return <main className="component-lab container"><header className="component-lab__header"><div><span className="eyebrow">DEV ONLY · COMPONENT LAB</span><h1>Castro’s Design System</h1><p>Laboratório de implementação e QA. Não é uma página pública de produto.</p></div><Badge tone="accent">Foundation</Badge></header>
    <div className="component-lab__grid">
      <section className="component-lab__section"><h2>Primitives</h2><div className="component-lab__row"><Button>Primário <Plus size={16} /></Button><Button variant="secondary">Secundário</Button><Button variant="tertiary">Terciário</Button><Button variant="destructive"><Trash2 size={16} />Destrutivo</Button><IconButton label="Mais opções"><MoreHorizontal size={18} /></IconButton><Button loading>Carregando</Button></div><Divider label="Campos" /><div className="component-lab__fields"><TextField id="lab-name" label="Nome" description="Descrição auxiliar do campo." placeholder="[CONTENT TBD]" required /><Textarea id="lab-message" label="Mensagem" error="Mensagem de exemplo para validação." /><Select id="lab-select" label="Estado" defaultValue=""><option value="" disabled>Escolha uma opção</option><option value="tbd">[A confirmar]</option></Select></div><div className="component-lab__choices"><Checkbox id="lab-check" label="Aceito a opção" description="Estado selecionável." defaultChecked /><Radio id="lab-radio-a" name="lab-radio" label="Opção A" /><Radio id="lab-radio-b" name="lab-radio" label="Opção B" /><Switch id="lab-switch" label="Ativo" description="Estado de switch." defaultChecked /></div><div className="component-lab__row"><Badge>Neutro</Badge><Badge tone="success">Ativo</Badge><Badge tone="warning">Pendente</Badge><Badge tone="danger">Erro</Badge><Avatar name="Castro’s Services" /><Spinner /><Skeleton width="10rem" /></div></section>
      <section className="component-lab__section"><h2>Feedback e overlays</h2><div className="component-lab__stack"><Alert title="Informação">Mensagem neutra para validar o padrão de feedback.</Alert><Alert tone="success" title="Concluído">Estado de sucesso estrutural.</Alert><Alert tone="warning" title="Atenção">Estado de atenção estrutural.</Alert><Alert tone="danger" title="Erro"><Info size={0} aria-hidden="true" />Estado de erro estrutural.</Alert><div className="component-lab__row"><Button onClick={() => setDialog(true)}>Dialog</Button><Button variant="secondary" onClick={() => setDrawer(true)}>Drawer</Button><Button variant="secondary" onClick={() => setSheet(true)}>Bottom sheet</Button><Popover label="Popover">Conteúdo contextual sem dados de negócio.</Popover><Tooltip label="Tooltip acessível"><Info size={18} /></Tooltip><DropdownMenu label="Menu"><button type="button">Ação estrutural</button></DropdownMenu></div><EmptyState title="Estado vazio">Não existem dados confirmados para apresentar.</EmptyState><LoadingState /><ErrorState /></div><Dialog open={dialog} title="Dialog de teste" onClose={() => setDialog(false)}>Conteúdo do dialog para validar Escape, foco e fullscreen mobile.</Dialog><Drawer open={drawer} title="Drawer de teste" onClose={() => setDrawer(false)}>Conteúdo do drawer para validar recomposição mobile.</Drawer><BottomSheet open={sheet} title="Bottom sheet de teste" onClose={() => setSheet(false)}>Conteúdo da sheet para filtros mobile.</BottomSheet><ConfirmDialog open={false} title="Confirmar ação" description="Descrição neutra de confirmação." onClose={() => undefined} onConfirm={() => undefined} /></section>
      <section className="component-lab__section"><h2>Navegação, filtros e booking</h2><div className="component-lab__stack"><Breadcrumbs items={[{ label: 'Início', href: '/' }, { label: 'Laboratório' }]} /><Tabs items={[{ id: 'one', label: 'Primeira tab', content: <p>Conteúdo da tab.</p> }, { id: 'two', label: 'Segunda tab', content: <p>Conteúdo da segunda tab.</p> }]} /><SearchToolbar onClear={() => setChips([])}><FilterGroup label="Estado"><FilterButton>Estado</FilterButton></FilterGroup></SearchToolbar><ActiveFilterChips items={chips} onRemove={(id) => setChips((items) => items.filter((item) => item.id !== id))} /><BookingStepper current="time" /><CalendarFoundation monthLabel="Mês a confirmar" /><DatePicker /><TimeSlotGroup label="Horários" slots={[{ id: 'one', label: '09:00' }, { id: 'two', label: '10:30', state: 'booked' }, { id: 'three', label: '12:00', state: 'disabled' }]} /><Pagination page={1} totalPages={3} onChange={() => undefined} /></div></section>
      <section className="component-lab__section"><h2>Dados e forms</h2><div className="component-lab__stack"><ResponsiveEntityList columns={[{ key: 'name', label: 'Nome', render: (row) => row.name }, { key: 'status', label: 'Estado', render: (row) => <Badge>{row.status}</Badge> }]} rows={rows} getRowKey={(row) => row.id} renderMobile={(row) => <EntityCard title={row.name}><Badge>{row.status}</Badge></EntityCard>} /><DefinitionList items={[{ term: 'Estado', description: '[A confirmar]' }, { term: 'Descrição', description: '[CONTENT TBD]' }]} /><ActivityList items={[{ id: '1', title: 'Atividade', detail: '[A confirmar]', time: '[A confirmar]' }]} /><FormSection title="Dados" description="Padrão de secção de formulário."><TextField id="lab-email" label="Email" type="email" /><SearchInput placeholder="Pesquisar no laboratório" /></FormSection><FormActions><Button variant="secondary">Cancelar</Button><Button>Guardar</Button></FormActions><FormSummary><p>Resumo estrutural sem dados de negócio.</p></FormSummary></div></section>
    </div></main>
}
